name: Build React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: controll-view/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: controll-view

      - name: Run tests
        run: npm run test -- --coverage --watchAll=false
        working-directory: controll-view

      - name: Build React app
        run: npm run build
        working-directory: controll-view

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build-${{ github.sha }}
          path: controll-view/build/
          retention-days: 30

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.sha }}
          path: controll-view/coverage/
          retention-days: 7