name: Build React App

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: controll-view/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: controll-view

      - name: Build React app
        run: npm run build
        working-directory: controll-view

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build-${{ github.sha }}
          path: controll-view/build/
          retention-days: 30

      - name: Notify Jenkins on success
        if: success() && github.ref == 'refs/heads/release'
        run: |
          curl -X POST "${{ secrets.JENKINS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "artifact_name": "react-build-${{ github.sha }}",
              "run_id": "${{ github.run_id }}"
            }'
